apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: 2.9.3
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  values:
    persistence:
      enabled: true
  interval: 5m
  install:
    createNamespace: true
