apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age-private-key: |
    -----BEGIN AGE KEY-----
    # the entire contents of ~/.sops-keys/age.key
    public key: age1h5htcp8zwmtwfkp647xa48xlggpmmnmva6dm837w5pemfx6zu5ssxhnhjj
AGE-SECRET-KEY-1NRPL7U9J0DNAF8FCWXKZM40AQ4K5CNYSM0C0LRG06DKU0UM5VZNSR2SZQ6
    ...
    -----END AGE KEY-----

